apiVersion: v1
kind: Service
metadata:
  name: ry-auth
  namespace: ruoyi-basic
spec:
  selector:
    app: ry-auth
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP