apiVersion: v1
kind: Service
metadata:
  name: ry-gateway
  namespace: ruoyi-basic
spec:
  selector:
    app: ry-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP