apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: ruoyi-basic
data:
  mysql.host: "mysql-master"
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "123"