apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-0
  labels:
    app: nacos
    nacos-name: nacos-0    # 添加唯一标识
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nacos/nacos-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-1
  labels:
    app: nacos
    nacos-name: nacos-1    # 添加唯一标识
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nacos/nacos-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-2
  labels:
    app: nacos
    nacos-name: nacos-2    # 添加唯一标识
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nacos/nacos-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc-0
  namespace: ruoyi-basic
  labels:
    app: nacos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nacos
      nacos-name: nacos-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc-1
  namespace: ruoyi-basic
  labels:
    app: nacos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nacos
      nacos-name: nacos-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc-2
  namespace: ruoyi-basic
  labels:
    app: nacos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nacos
      nacos-name: nacos-2