apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ruoyi-basic
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog_format=ROW
    default_storage_engine=innodb
    default_authentication_plugin=mysql_native_password
    require_secure_transport=OFF

  slave.cnf: |
    [mysqld]
    server-id=2
    log-bin=mysql-bin
    binlog_format=ROW
    default_storage_engine=innodb
    default_authentication_plugin=mysql_native_password