apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
  namespace: ruoyi-basic
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql/data-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  namespace: ruoyi-basic
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql/data-1