apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: ruoyi-basic
spec:
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: mysql-0
  ports:
    - port: 3306
      targetPort: 3306