apiVersion: v1
kind: Service
metadata:
  name: ruoyi-mysql
  namespace: ruoyi-basic
  labels:
    app: ruoyi-mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: ruoyi-mysql
