apiVersion: v1
kind: Service
metadata:
  name: ruoyi-mysql
  namespace: ruoyi-basic
  labels:
    app: ruoyi-mysql
spec:
  ports:
    - name: "tcp"
      port: 3306
      targetPort: 3306
      nodePort: 30006
  selector:
    app: ruoyi-mysql
  type: NodePort