apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: ruoyi-basic
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          command:
            - "redis-server"
            - "/etc/redis/redis.conf"
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-conf
              mountPath: /etc/redis
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-redis-0
        - name: redis-conf
          configMap:
            name: redis-conf-cm
            items:
              - key: redis.conf
                path: redis.conf